"""remove provider_name from generations

Revision ID: d7c16af77c9e
Revises: 553dc6a50a20
Create Date: 2025-10-22 17:47:29.312285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7c16af77c9e"
down_revision: Union[str, Sequence[str], None] = "553dc6a50a20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop schema_migrations table if it exists (from legacy migration system)
    op.execute("DROP TABLE IF EXISTS schema_migrations")
    op.drop_column("generations", "provider_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then update existing rows, then make it NOT NULL
    op.add_column(
        "generations",
        sa.Column(
            "provider_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    # Set a default value for existing rows (though this downgrade should rarely be used)
    op.execute(
        "UPDATE generations SET provider_name = 'unknown' WHERE provider_name IS NULL"
    )
    # Now make it NOT NULL
    op.alter_column("generations", "provider_name", nullable=False)
    op.create_table(
        "schema_migrations",
        sa.Column(
            "version", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "applied_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "execution_time_ms", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "applied_by", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_migrations_pkey")),
    )
    # ### end Alembic commands ###
