"""
Core logic for creating Supabase users and invite records,
and optionally sending activation links via Twilio SMS.

Ported from friends-and-family-supabase/backend/admin.py.
"""

from __future__ import annotations

import datetime
from typing import TYPE_CHECKING

from boards.logging import get_logger

if TYPE_CHECKING:
    from supabase import Client

from supabase_auth.types import AdminUserAttributes

logger = get_logger(__name__)


def create_user_if_not_exists(supabase_client: Client, phone: str) -> str | None:
    """Create a Supabase auth user for the given phone number, or find existing.

    Uses a dummy email convention ({digits}@example.com) since Supabase
    requires an email for user creation.

    Returns the user ID or None on failure.
    """
    if not phone.startswith("+"):
        logger.error("Phone must start with +", phone=phone)
        return None

    dummy_email = f"{phone.replace('+', '')}@example.com"

    try:
        attributes: AdminUserAttributes = {
            "email": dummy_email,
            "phone": phone,
            "email_confirm": True,
            "phone_confirm": True,
            "user_metadata": {"phone": phone},
        }
        user = supabase_client.auth.admin.create_user(attributes)
        logger.info("Created new user", user_id=user.user.id, phone=phone)
        return user.user.id
    except Exception as e:
        logger.debug("User creation failed, searching for existing user", error=str(e))
        try:
            users_response = supabase_client.auth.admin.list_users()
            for u in users_response:
                if u.phone == phone:
                    logger.info("Found existing user", user_id=u.id, phone=phone)
                    return u.id

            logger.error("Could not create or find user", phone=phone, error=str(e))
            return None
        except Exception as search_err:
            logger.error("Error searching for user", error=str(search_err))
            return None


def create_invite(supabase_client: Client, phone: str) -> str | None:
    """Create an invite record for the given phone number.

    Creates the Supabase user if it doesn't exist, then inserts an invite
    row with a 2-week expiry. The invite code is auto-generated by the database.

    Returns the invite code or None on failure.
    """
    user_id = create_user_if_not_exists(supabase_client, phone)
    if not user_id:
        logger.error("Could not get user ID for invite", phone=phone)
        return None

    expires_at = (datetime.datetime.utcnow() + datetime.timedelta(weeks=2)).isoformat()
    data = {"user_id": user_id, "expires_at": expires_at}

    try:
        response = supabase_client.table("invites").insert(data).execute()
        if response.data:
            invite = response.data[0]
            code = invite["code"]
            logger.info("Invite created", phone=phone, code=code)
            return code
        else:
            logger.error("Failed to create invite record (no data returned)", phone=phone)
            return None
    except Exception as e:
        logger.error("Error creating invite record", phone=phone, error=str(e))
        return None


def send_sms(
    phone: str,
    code: str,
    base_url: str,
    twilio_sid: str,
    twilio_token: str,
    twilio_from: str,
) -> bool:
    """Send an activation link via Twilio SMS.

    Returns True on success, False on failure.
    """
    try:
        from twilio.rest import Client as TwilioClient
    except ImportError:
        logger.error(
            "twilio package not installed. "
            "Install with: pip install weirdfingers-boards[sms-twilio]"
        )
        return False

    url = f"{base_url}/activate?code={code}"
    body = f"You are invited! Click here to login: {url}"

    try:
        client = TwilioClient(twilio_sid, twilio_token)
        message = client.messages.create(body=body, from_=twilio_from, to=phone)
        logger.info("SMS sent", phone=phone, message_sid=message.sid)
        return True
    except Exception as e:
        logger.error("Error sending SMS", phone=phone, error=str(e))
        return False
