import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "installation",
    {
      type: "category",
      label: "Installation Guides",
      collapsed: false,
      items: [
        "installation/installing-baseboards",
        "installation/cloning-repository",
        "installation/custom-application",
      ],
    },
    {
      type: "category",
      label: "Baseboards",
      collapsed: false,
      items: [
        "baseboards/overview",
      ],
    },
    {
      type: "category",
      label: "Backend Development",
      collapsed: false,
      items: [
        "backend/index",
        "backend/getting-started",
        {
          type: "category",
          label: "GraphQL API",
          collapsed: true,
          items: [
            "backend/graphql-api",
            "backend/graphql-api/types",
            "backend/graphql-api/queries",
            "backend/graphql-api/mutations",
            "backend/graphql-api/access-control",
          ],
        },
        "backend/storage",
        "backend/migrations",
        "backend/testing",
      ],
    },
    {
      type: "category",
      label: "Frontend Development",
      collapsed: false,
      items: [
        "frontend/getting-started",
        "frontend/configuration",
        "frontend/uploading-artifacts",
        "frontend/ui-examples",
        "frontend/realtime",
        "frontend/testing",
      ],
    },
    {
      type: "category",
      label: "Authentication & Authorization",
      collapsed: false,
      items: [
        "auth/overview",
        {
          type: "category",
          label: "Backend",
          collapsed: true,
          items: [
            "auth/backend/auth-adapters",
            "auth/backend/authorization",
          ],
        },
        {
          type: "category",
          label: "Frontend",
          collapsed: true,
          items: [
            "auth/frontend/getting-started",
          ],
        },
        {
          type: "category",
          label: "Auth Providers",
          collapsed: true,
          items: [
            "auth/providers/none",
            "auth/providers/jwt",
            "auth/providers/supabase",
          ],
        },
        {
          type: "category",
          label: "Multi-Tenancy",
          collapsed: true,
          items: [
            "auth/multi-tenant",
            "auth/tenant-setup",
            "auth/tenant-management-api",
            "auth/multi-tenant-deployment",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Generators",
      collapsed: false,
      items: [
        "generators/overview",
        "generators/getting-started",
        "generators/creating-generators",
        "generators/configuration",
        "generators/artifact-types",
        "generators/testing",
        "generators/examples",
        "generators/api-reference",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
  ],
};

export default sidebars;
