import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'installation',
    {
      type: 'category',
      label: 'Backend Development',
      collapsed: false,
      items: [
        'backend/getting-started',
        'backend/migrations',
      ],
    },
    {
      type: 'category',
      label: 'Frontend Development',
      collapsed: false,
      items: [
        'frontend/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Providers',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'providers'},
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'deployment'},
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'guides'},
      ],
    },
  ],
};

export default sidebars;
