name: Release

on:
  release:
    types: [published]

jobs:
  detect-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.detect.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect packages from tag
        id: detect
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ $TAG == backend@* ]]; then
            echo "packages=[\"backend\"]" >> $GITHUB_OUTPUT
          elif [[ $TAG == frontend@* ]]; then
            echo "packages=[\"frontend\"]" >> $GITHUB_OUTPUT
          else
            echo "packages=[]" >> $GITHUB_OUTPUT
          fi

  release-python:
    needs: detect-packages
    if: contains(needs.detect-packages.outputs.packages, 'backend')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Extract version from tag
        id: version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#backend@}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update version in src/boards/__init__.py safely
        shell: bash
        run: |
          cd packages/backend
          python - <<'PY'
          import re
          import sys
          import os

          version = os.environ.get('VERSION', '')
          if not version:
              print("Error: VERSION not set", file=sys.stderr)
              sys.exit(1)

          # Validate semver format
          if not re.match(r'^\d+\.\d+\.\d+$', version):
              print(f"Error: Invalid version format: {version}", file=sys.stderr)
              sys.exit(1)

          p = 'src/boards/__init__.py'
          try:
              content = open(p).read()
              content = re.sub(r"__version__\s*=\s*\"[^\"]*\"", f'__version__ = "{version}"', content)
              open(p, 'w').write(content)
          except Exception as e:
              print(f"Error updating version: {e}", file=sys.stderr)
              sys.exit(1)
          PY
        env:
          VERSION: ${{ steps.version.outputs.version }}
      - name: Build package
        run: |
          cd packages/backend
          uv build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd packages/backend
          uv publish

  release-npm:
    needs: detect-packages
    if: contains(needs.detect-packages.outputs.packages, 'frontend')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Extract version from tag
        id: version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#frontend@}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update version
        run: |
          cd packages/frontend
          pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: |
          cd packages/frontend
          pnpm build
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/frontend
          pnpm publish --access public
